server:
  port: 8084

spring:
  datasource:
    url: jdbc:mariadb://${DB_URL}/openlab?serverTimezone=Asia/Seoul&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true